# Generated by Django 4.0.6 on 2022-08-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_task_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='name',
        ),
    ]
