# Generated by Django 4.0.6 on 2022-08-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='my_app.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='my_app.airport'),
        ),
    ]
